#################### Default Setup ####################
wandb: False
seed: 0
enable_benchmark: True
use_amp: True
multiprocessing: False
main_gpu: '1'
num_workers: 0
pin_memory: True
refactoring: True
verbose: False
# method_name: FedAvg
remark: ""

checkpoint_path: './checkpoints'
exp_name: base
output_model_path: 'res18.pt'
save_freq: 20
batch_size: 32
save_test: True

## Resume
load_model_path: False      # ====> may be like ./checkpoints/CIFAR100/iid/iid_base/res18.pt. use command line +load_model_path=(path)
wandb_resume_id: False


###### wandb && logging ######
project: "FedRCL"
log_dir: './checkpoints' 


#################### Data Split ####################
split:
  mode: 'dirichlet'
  alpha: 0.3
  class_per_client: 0 # only for skew mode
  unbalanced: False
  overlap_ratio: 0.0
  create_client_dataset: True

#################### Optimizer ####################
optimizer:
  name: sgd
  momentum: 0.9
  wd: 1e-4


#################### Eval ####################
eval:
  freq: 1
  batch_size: 64

analysis: True


defaults:
  - trainer: base
  - client: base
  - evaler: base
  - dataset: brain_dataset
  - _self_
  - server: base
  - model: resnet18
  - override hydra/job_logging: default